CREATE SCHEMA avaliacao CHARACTER SET utf8 COLLATE utf8_general_ci;
USE avaliacao;

CREATE TABLE Contato (
  id INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NULL,
  sobrenome VARCHAR(100) NULL,
  nascimento DATE NULL,
  email VARCHAR(100) NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE Empresa (
  id INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NULL,
  cnpj VARCHAR(40) NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE Proccess (
  id INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  codflow  INT(20) NULL,
  proccess VARCHAR(80) NULL,
  description TEXT NULL,
  PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE Contato_Empresa  (
  Contato_id INT(18) UNSIGNED NOT NULL,
  Empresa_id INT(18) UNSIGNED NOT NULL,
  CONSTRAINT ContatoEmpresa FOREIGN KEY (Contato_id)REFERENCES Contato (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT EmpresaContato FOREIGN KEY (Empresa_id)REFERENCES Empresa (id) ON DELETE NO ACTION ON UPDATE NO ACTION 
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Correspondencia (
  id INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  Contato_id INT(18) UNSIGNED NOT NULL,
  datahora DATETIME NULL,
  PRIMARY KEY(id),
  CONSTRAINT CorrespondenciaContato FOREIGN KEY (Contato_id)REFERENCES Contato (id) ON DELETE NO ACTION ON UPDATE NO ACTION 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;



ALTER TABLE Contato
ADD telefone VARCHAR(80) NULL;

ALTER TABLE Contato
ADD celular VARCHAR(80) NULL;

CREATE TABLE Funcionario (
  id INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(80) NULL,
  Empresa_id INT(18) UNSIGNED NOT NULL,
  cep VARCHAR(100) NULL,
  endereco VARCHAR(200) NULL,
  bairro VARCHAR(80) NULL,
  cidade VARCHAR(80) NULL,
  estado VARCHAR(80) NULL,
  PRIMARY KEY(id),
  CONSTRAINT FuncionarioEmpresa FOREIGN KEY (Empresa_id)REFERENCES Empresa (id) ON DELETE NO ACTION ON UPDATE NO ACTION 
)ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;





